### PR TITLE
Biblatex support

### PR DESCRIPTION
**Pull request by ashwinvis**
Copy all new entry types defined in biblatex.rsc
As defined in: 

https://github.com/ge-ne/bibtool/blob/fb251d0130e0bda33dfa9b64a59e1eb4b84979b0/lib/biblatex.rsc#L29-L85

### CODE REVIEW

**Comment by msprev** [comment]
Rather than cut and paste this from the bibtool codebase, would adding this work instead in the rsc?

```
resource{biblatex}
```

see bibtool docs pp. 20-21 for the command, which seems to do what you want.

I'm not sure if this change would interfere with expected behaviour on normal BibTeX files.

**Comment by ashwinvis** [comment]
I just did that. And it works. I don't think it will break detection of entries. As biblatex simply extends bibtex, afaik. I am not sure what crossref.map does

https://github.com/ge-ne/bibtool/blob/fb251d0130e0bda33dfa9b64a59e1eb4b84979b0/lib/biblatex.rsc#L232-L301

Does it apply to you?

**Comment by msprev** [comment]
Great, thanks for this! I've merged it now. Let me know if you find any problems.

**Comment by msprev** [comment]
I tested it and had to revert to the previous method as it wasn't working correctly. This is fairly clunky but at least adds basic BibLaTeX support and handles it through the default formatter.

**Pull request merged**
